os:
- osx
language: objective-c
compiler:
- clang
before_install:
- brew update > /dev/null
- brew outdated autoconf || brew upgrade autoconf
- brew outdated automake || brew upgrade automake
- brew outdated libtool || brew upgrade libtool
- git clone https://github.com/bfabiszewski/libmobi.git
- ( cd libmobi && ./autogen.sh && ./configure && make && sudo make install )
- git config --global user.name "Travis CI (QLMobi)"
- git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
script:
- xcodebuild
